version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    environment:
      - POSTGRES_URL=postgresql+psycopg://app:app@db:5432/app
      - REDIS_URL=redis://redis:6379/0
      - TZ=Europe/London
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
    environment:
      - API_BASE=http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
-NoNewline
