name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Build and run
      run: docker compose -f infra/docker-compose.yml up --build -d
    - name: Backend tests
      run: docker compose -f infra/docker-compose.yml exec -T backend pytest -q
    - name: Teardown
      if: always()
      run: docker compose -f infra/docker-compose.yml down -v